import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";
import { SocioProvider } from './Context/socioContext'; // Ajusta la ruta según tu contexto
import { MovimientoProvider } from './Context/movContext';

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="es">
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <SocioProvider>
          <MovimientoProvider>
            <NavBar />
            <main>
              {children}
            </main>
          </MovimientoProvider>
        </SocioProvider>
      </body>
    </html>
  );
}
