'use client';

import { usePathname } from 'next/navigation';
import localFont from "next/font/local";
import "./globals.css";
import NavBar from "./NavBar";
import { SocioProvider } from './Context/socioContext'; // Ajusta la ruta según tu contexto
import { MovimientoProvider } from './Context/movContext';
import { RepresentanteProvider } from './Context/representanteContext';
import ProvidersWrapper from './Context/ProviderWrapper';
// import Link from "next/link";
import { IoMdArrowRoundBack } from "react-icons/io";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export function useCurrentPath() {
  const pathName = usePathname();
  return pathName;
}

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const providers = [RepresentanteProvider, SocioProvider, MovimientoProvider];

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = useCurrentPath(); // Using the custom hook to get the current pathname
  const isHomePage = pathname === '/';
  return (
    <html lang="es">
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ProvidersWrapper providers={providers}>
          <NavBar />
          <main>
            <head>
              <title>{"Coopesoft"}</title>
              <meta name="description" content={"Coopesoft"} />
            </head>
            {!isHomePage && ( // Solo renderiza el botón si no estamos en la página principal
              <button
                onClick={() => window.history.back()}
                className="text-[#00755D] hover:text-[#e6be31] pl-6"
              >
                <IoMdArrowRoundBack className="inline-block" size={25} />
              </button>
            )}
            {children}
          </main>
        </ProvidersWrapper>
      </body>
    </html>
  );
}
